//USER CONSTANTS
export const GET_DASHBOARD_INFO = 'GET_DASHBOARD_INFO'; 
export const GET_ALL_USERS = 'GET_ALL_USERS '; 
export const GET_ROLES = 'GET_ROLES';
export const GET_SITES = 'GET_SITES';
export const GET_ESCALATION = 'GET_ESCALATION';
export const GET_USER_INFO = 'GET_USER_INFO';


//SHIFTS CONSTANTS
export const GET_SHIFTS = 'GET_SHIFTS';
export const GET_SHIFT_INFO = 'GET_SHIFT_INFO';

//COMMON PARAMS CONSTANTS
export const GET_PARAMS = 'GET_PARAMS';
export const GET_TIMEZONES = 'GET_TIMEZONES';
export const GET_LANGUAGES = 'GET_LANGUAGES';