//USER CONSTANTS
export const GET_DASHBOARD_INFO = 'GET_DASHBOARD_INFO'; 
export const GET_ALL_USERS = 'GET_ALL_USERS '; 
export const GET_ROLES = 'GET_ROLES';
export const GET_SITES = 'GET_SITES';
export const GET_ESCALATION = 'GET_ESCALATION';
export const GET_USER_INFO = 'GET_USER_INFO';

//SHIFTS CONSTANTS
export const GET_SHIFTS = 'GET_SHIFTS';
export const GET_SHIFT_INFO = 'GET_SHIFT_INFO';

//COMMON PARAMS CONSTANTS
export const GET_PARAMS = 'GET_PARAMS';
export const GET_TIMEZONES = 'GET_TIMEZONES';
export const GET_LANGUAGES = 'GET_LANGUAGES';

//UOM CONSTANTS
export const GET_UOM = 'GET_UOM';

//DISPLAY CONSTANTS
export const GET_DISPLAY = 'GET_DISPLAY';

//REASONS CONSTANTS
export const GET_REASONS = 'GET_REASONS';
export const GET_REASONS_BY_SITE = 'GET_REASONS_BY_SITE';

//BREAK CONSTANTS
export const GET_BREAK = 'GET_BREAK';
export const GET_BREAK_BY_SITE = 'GET_BREAK_BY_SITE';

//WORKCELL CONSTANTS
export const GET_WORKCELLS = 'GET_WORKCELLS';

//ASSETS CONSTANTS
export const GET_ASSETS = 'GET_ASSETS';

//TAG CONSTANTS
export const GET_TAGS = 'GET_TAGS';
