CREATE TABLE [dbo].[Shift] (
    [shift_id]               INT            IDENTITY (1, 1) NOT NULL,
    [shift_code]             NVARCHAR (100) NOT NULL,
    [shift_name]             NVARCHAR (200) NOT NULL,
    [shift_description]      NVARCHAR (256) NULL,
    [shift_sequence]         INT            NOT NULL,
    [start_time]             TIME (0)       NOT NULL,
    [start_time_offset_days] INT            DEFAULT ((0)) NOT NULL,
    [end_time]               TIME (0)       NOT NULL,
    [end_time_offset_days]   INT            DEFAULT ((0)) NOT NULL,
    [duration_in_minutes]    INT            NOT NULL,
    [valid_from]             DATETIME       NOT NULL,
    [valid_to]               DATETIME       NULL,
    [team_code]              NVARCHAR (100) NULL,
    [is_first_shift_of_day]  BIT            NOT NULL,
    [status]                 VARCHAR (50)   NOT NULL,
    [entered_by]             NVARCHAR (100) CONSTRAINT [DF_Shift_entered_by] DEFAULT (N'SQL Manual Entry') NOT NULL,
    [entered_on]             DATETIME       CONSTRAINT [DF_Shift_entered_on] DEFAULT (getdate()) NOT NULL,
    [last_modified_by]       NVARCHAR (100) CONSTRAINT [DF_Shift_last_modified_by] DEFAULT (N'SQL Manual Entry') NOT NULL,
    [last_modified_on]       DATETIME       CONSTRAINT [DF_Shift_last_modified_on] DEFAULT (getdate()) NOT NULL,
    [asset_id]               INT            NOT NULL,
    CONSTRAINT [PK_Shift_Shift_Id] PRIMARY KEY CLUSTERED ([shift_id] ASC),
    CONSTRAINT [FK_Shift_Asset_Id] FOREIGN KEY ([asset_id]) REFERENCES [dbo].[Asset] ([asset_id]),
    CONSTRAINT [UNC_Shift_Shift_Code] UNIQUE NONCLUSTERED ([shift_code] ASC)
);

