CREATE TABLE [dbo].[Tag] (
    [tag_id]           INT            IDENTITY (1, 1) NOT NULL,
    [tag_code]         NVARCHAR (100) NOT NULL,
    [tag_name]         NVARCHAR (200) NOT NULL,
    [tag_description]  NVARCHAR (256) NULL,
    [tag_group]        NVARCHAR (100) NULL,
    [datatype]         NVARCHAR (100) NULL,
    [tag_type]         NVARCHAR (100) NULL,
    [UOM_code]         NVARCHAR (100) NOT NULL,
    [rollover_point]   FLOAT (53)     NOT NULL,
    [aggregation]      NVARCHAR (100) NULL,
    [status]           VARCHAR (50)   NOT NULL,
    [entered_by]       NVARCHAR (100) CONSTRAINT [DF_Tag_entered_by] DEFAULT (N'SQL Manual Entry') NOT NULL,
    [entered_on]       DATETIME       CONSTRAINT [DF_Tag_entered_on] DEFAULT (getdate()) NOT NULL,
    [last_modified_by] NVARCHAR (100) CONSTRAINT [DF_Tag_last_modified_by] DEFAULT (N'SQL Manual Entry') NOT NULL,
    [last_modified_on] DATETIME       CONSTRAINT [DF_Tag_last_modified_on] DEFAULT (getdate()) NOT NULL,
    [site_id]          INT            NOT NULL,
    [asset_id]         INT            NOT NULL,
    [max_change]       INT            NOT NULL,
    CONSTRAINT [PK_Tag_Tag_Id] PRIMARY KEY CLUSTERED ([tag_id] ASC),
    CONSTRAINT [FK_Tag_Asset_Id] FOREIGN KEY ([asset_id]) REFERENCES [dbo].[Asset] ([asset_id]),
    CONSTRAINT [FK_Tag_UOM_Code] FOREIGN KEY ([UOM_code]) REFERENCES [dbo].[UOM] ([UOM_code]),
    CONSTRAINT [UNC_Tag_Tag_Code] UNIQUE NONCLUSTERED ([tag_code] ASC),
    CONSTRAINT [UNC_Tag_Tag_Name] UNIQUE NONCLUSTERED ([tag_name] ASC)
);

