FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build
WORKDIR /src
COPY ["WebAPIModule.csproj", "./"]
RUN dotnet restore "./WebAPIModule.csproj"
COPY . .
RUN dotnet build "WebAPIModule.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebAPIModule.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebAPIModule.dll"]